kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myculinaryblog-content
  namespace: myculinaryblog
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
