---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-new-deployment.yaml
  - 02-service.yaml
  - 03-myculinaryblog-route.yaml
  - 04-www-myculinaryblog-route.yaml
  - 05-pvc-content.yaml
  - 06-pvc-db.yaml
